language: ruby
rvm:
- 2.2

cache:
- bundler
- directories:
  - .asset-cache
  - _assets/bower
  - node_modules

notifications:
  email: webmaster@baharboutique.com

before_install:
- #gem install travis_dedup && travis-dedup $TRAVIS_REPO_SLUG $TRAVIS_ACCESS_TOKEN --branches
- nvm install 4
- npm install -g bower
- if [[ $(git show --name-only) == *_assets/less* ]]; then echo "LESS changed. Clearing cache..."; rm -rf .asset-cache/sprockets; fi

script:
- set -e
- bower install
- bundle exec jekyll build
- set +e
- bundle exec htmlproofer ./_site  --only-4xx --assume-extension --allow-hash-href --check-html --http-status-ignore 0
- cd _site
- touch .nojekyll
- git init
- git config user.name "Travis-CI"
- git config user.email "travis@baharboutique.com"
- git add .
- git commit -m "Deployed to Github Pages" >/dev/null
- git push --force --quiet "https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG" master > /dev/null 2>&1

git:
  depth: 10

branches:
  only:
  - source
