language: ruby
rvm:
- 2.2

cache:
- bundler
- directories:
  - .asset-cache
  - _assets/bower
  - node_modules

notifications:
  email: webmaster@baharboutique.com

before_install:
- 'if [ "$TRAVIS_BUILD_NUMBER" != $(curl -H "Accept: application/vnd.travis-ci.2+json" https://api.travis-ci.org/repos/$TRAVIS_REPO_SLUG/branches/$TRAVIS_BRANCH | jq -r ".branch.number") ]; then echo -e "\e[33;1mThere are newer queued builds for this branch, failing early.\e[0m"; exit 1; fi'
- nvm install 4
- npm install -g bower
- if [[ $(git show --name-only) == *_assets/less* ]]; then echo "LESS changed. Clearing cache..."; rm -rf .asset-cache/sprockets; fi

script:
- set -e
- bower install
- bundle exec jekyll build
- set +e
- bundle exec htmlproofer ./_site  --only-4xx --assume-extension --allow-hash-href --check-html --http-status-ignore 0
- cd _site
- touch .nojekyll
- git init
- git config user.name "Travis-CI"
- git config user.email "travis@baharboutique.com"
- git add .
- git commit -m "Deployed to Github Pages" >/dev/null
- git push --force --quiet "https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG" master > /dev/null 2>&1

git:
  depth: 10

branches:
  only:
  - source
